# -*- coding: utf-8 -*-
"""Test_Units.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SWRuUixho3FJe5amdK2fkkzNuZ7odlza
"""

import unittest
import numpy as np

class TestIPLPrediction(unittest.TestCase):

    def test_score_predict(self):
        # Test Case 1
        batting_team_1 = 'Chennai Super Kings'
        bowling_team_1 = 'Mumbai Indians'
        runs_1 = 150
        wickets_1 = 3
        overs_1 = 15
        runs_last_5_1 = 40
        wickets_last_5_1 = 1
        predicted_score_1 = score_predict(batting_team_1, bowling_team_1, runs_1, wickets_1, overs_1, runs_last_5_1, wickets_last_5_1)
        self.assertEqual(predicted_score_1,predicted_score_1)

        # Test Case 2
        batting_team_2 = 'Kolkata Knight Riders'
        bowling_team_2 = 'Royal Challengers Bangalore'
        runs_2 = 180
        wickets_2 = 4
        overs_2 = 18
        runs_last_5_2 = 60
        wickets_last_5_2 = 2
        predicted_score_2 = score_predict(batting_team_2, bowling_team_2, runs_2, wickets_2, overs_2, runs_last_5_2, wickets_last_5_2)
        self.assertEqual(predicted_score_2,predicted_score_2)

        # Test Case 3
        batting_team_3 = 'Mumbai Indians'
        bowling_team_3 = 'Delhi Daredevils'
        runs_3 = 120
        wickets_3 = 2
        overs_3 = 12
        runs_last_5_3 = 30
        wickets_last_5_3 = 1
        predicted_score_3 = score_predict(batting_team_3, bowling_team_3, runs_3, wickets_3, overs_3, runs_last_5_3, wickets_last_5_3)
        self.assertEqual(predicted_score_3,predicted_score_3)

# Add try-except block to handle exceptions
if __name__ == '__main__':

  s = unittest.TestLoader().loadTestsFromTestCase(TestIPLPrediction)
  unittest.TextTestRunner().run(s)